
CREATE TABLE ADRESLER (
    ADRES_NO SERIAL PRIMARY KEY,
    CADDE VARCHAR(20),
    MAHALLE VARCHAR(20),
    BINA_NO VARCHAR(20),
    SEHIR VARCHAR(20),
    POSTA_KODU INT,
    ULKE VARCHAR(20)
);

CREATE TABLE UYELER (
    UYE_NO SERIAL PRIMARY KEY,
    UYE_ADI VARCHAR(20),
    UYE_SOYADI VARCHAR(20),
    CINSIYET VARCHAR(5),
    TELEFON VARCHAR(15),
    EPOSTA VARCHAR(40),
    ADRES_NO INT REFERENCES ADRESLER(ADRES_NO)
);

CREATE TABLE EMANET (
    EMANET_NO SERIAL PRIMARY KEY,
    ISBN VARCHAR(20) NOT NULL,
    UYE_NO INT NOT NULL,
    KUTUPHANE_NO INT NOT NULL,
    EMANET_TARIHI TIMESTAMP,
    TESLIM_TARIHI TIMESTAMP
);

CREATE TABLE KITAPLAR (
    ISBN VARCHAR(20) PRIMARY KEY,
    KITAP_ADI VARCHAR(20),
    YAYIN_TARIHI VARCHAR(20),
    S_SAYISI INT
);

CREATE TABLE YAZARLAR (
    YAZAR_NO SERIAL PRIMARY KEY,
    YAZAR_ADI VARCHAR(20),
    YAZAR_SOYADI VARCHAR(20)
);

CREATE TABLE KATEGORILER (
    KATEGORI_NO SERIAL PRIMARY KEY,
    KATEGORI_ADI VARCHAR(20)
);

CREATE TABLE KUTUPHANE (
    KUTUPHANE_NO SERIAL PRIMARY KEY,
    KUTUPHANE_ADI VARCHAR(20),
    ACIKLAMA VARCHAR(20),
    ADRES_NO INT REFERENCES ADRESLER(ADRES_NO)
);

CREATE TABLE KITAP_KUTUPHANE (
    KUTUPHANE_NO INT NOT NULL REFERENCES KUTUPHANE(KUTUPHANE_NO),
    ISBN VARCHAR(20) NOT NULL REFERENCES KITAPLAR(ISBN),
    MIKTAR INT,
    CONSTRAINT KITAP_KUTUPHANE_UNIQUE UNIQUE (KUTUPHANE_NO, ISBN),
    PRIMARY KEY (KUTUPHANE_NO, ISBN)
);

CREATE TABLE KITAP_KATEGORI (
    ISBN VARCHAR(20) NOT NULL REFERENCES KITAPLAR(ISBN),
    KATEGORI_NO INT NOT NULL REFERENCES KATEGORILER(KATEGORI_NO),
    PRIMARY KEY (KATEGORI_NO, ISBN)
);

CREATE TABLE KITAP_YAZAR (
    ISBN VARCHAR(20) NOT NULL REFERENCES KITAPLAR(ISBN),
    YAZAR_NO INT NOT NULL REFERENCES YAZARLAR(YAZAR_NO),
    PRIMARY KEY (YAZAR_NO, ISBN)
);

